version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mondo-db'
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - '27017-27019:27017-27019'

  server:
    image: registry.digitalocean.com/dsd-paas-cr/todoapp:latest
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - database
