name: CAAS deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_CONTAINER_REGISTRY_API_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Build image
        run: docker build -t registry.digitalocean.com/dsd-paas-cr/todoapp-caas:latest -f ./Dockerfile .
      - name: Push image
        run: docker push registry.digitalocean.com/dsd-paas-cr/todoapp-caas:latest
      - name: Copy files vis scp
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.yml,init.js"
          target: "~/todoapp"
      - name: Run the app
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/todoapp
            {
              echo "API_PORT=${{ secrets.API_PORT }}"
              echo "MONGODB_URI=${{ secrets.MONGODB_URI }}"
              echo "SECRET_OR_KEY=${{ secrets.SECRET_OR_KEY }}"
            } > .env
            docker compose down
            docker compose up --build -d
