name: IAAS deploy

on:
  # push:
  #   branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy files vis scp
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "."
          target: "/opt/todoapp"

      - name: Run the app
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /opt/todoapp
            npm i
            npm run build
            {
              echo "API_PORT=${{ secrets.API_PORT }}"
              echo "MONGODB_URI=${{ secrets.MONGODB_URI }}"
              echo "SECRET_OR_KEY=${{ secrets.SECRET_OR_KEY }}"
            } >> .env
            npm run start
