name: PAAS deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_CONTAINER_REGISTRY_API_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Build image
        run: docker build -t registry.digitalocean.com/dsd-paas-cr/todoapp:latest -f ./Dockerfile .
      - name: Push image
        run: docker push registry.digitalocean.com/dsd-paas-cr/todoapp:latest
